const actionTypes = {
  GET_HOME: "GET_HOME",
  NEW_RELEASE: "NEW_RELEASE",
  GENRE: "GENRE",
  SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
  LOADING: "LOADING",
  USER: "USER",
  PLUSER: "PLUSER",
  SONGINFO: "SONGINFO",

  FAVORITE: "FAVORITE",

  // Album
  ALBUM: "ALBUM",

  //play music
  PLAY: "PLAY",
  SET_ALBUM: "SET_ALBUM",
  PLAYLIST: "PLAYLIST",
  SEARCH: "SEARCH",
  ISLOGIN: "ISLOGIN",
  ISREGISTER: "ISREGISTER",
  LOGIN: "LOGIN",
  NEW_SONG: "NEW_SONG",
  //Save
  SAVE_LOGIN: "SAVE_LOGIN",
  IMG: "IMG",
  CHECK_DELELE: "CHECK_DELELE",
  CHECK_ADD_SONG: "CHECK_ADD_SONG",

  // admin
  ADMIN_ADD: "ADMIN_ADD",
  ADMIN_EDIT: "ADMIN_EDIT",
  ADMIN_EDIT_ARTIST: "ADMIN_EDIT_ARTIST",
  ADMIN_EDIT_RELOAD_ARTIST: "ADMIN_EDIT_RELOAD_ARTIST",
  ADMIN_EDIT_RELOAD: "ADMIN_EDIT_RELOAD",
  ADMIN_ADD_ARTIST: "ADMIN_ADD_ARTIST",
  ADMIN_ADD_ASONG: "ADMIN_ADD_ASONG",
  CHECK_ADD_ARTIST: "CHECK_ADD_ARTIST",

  ADMIN_ADD_GENRE: "ADMIN_ADD_GENRE",
  CHECK_ADD_GENRE: "CHECK_ADD_GENRE",
  CHECK_ADD_SONG_GENRE: "CHECK_ADD_SONG_GENRE",
  ADMIN_EDIT_GENRE: "ADMIN_EDIT_GENRE",
  ADMIN_ASONG_GENRE: "ADMIN_ASONG_GENRE",

  // ADMIN playlist
  ADMIN_ADD_PLAYLIST: "ADMIN_ADD_PLAYLIST",
  CHECK_ADD_PLAYLIST: "CHECK_ADD_PLAYLIST",
  CHECK_ADD_SONG_PLAYLIST: "CHECK_ADD_SONG_PLAYLIST",
  ADMIN_EDIT_PLAYLIST: "ADMIN_EDIT_PLAYLIST",
  ADMIN_ASONG_PLAYLIST: "ADMIN_ASONG_PLAYLIST",

  // comment
  CHECKREPL: "CHECKREPL",

  FORGET_PASSWORD: "FORGET_PASSWORD",

  // information
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  UPDATEINFO: "UPDATEINFO",
};

export default actionTypes;
